### PR TITLE
Added read file ability to GroceryInventory so now you can just write…

### PR DESCRIPTION
**Pull request by wenzhenw**
… in the menu items in Inventory.txt.

Format is Item name, Price, Quantity, separated by newlines.

Also highlighted issue in CustomerTest said to change package name to Entities.

### CODE REVIEW

**Comment by wenzhenw** [comment]
Inventory.txt has same issues as Account.txt, make sure to not have extra newlines and no extra spaces in Inventory.txt since GroceryInventory uses parseInt.

**Comment by Ratbuyer** [comment]
change package in test won't work i tried

**Review by Ratbuyer — APPROVED** [review]
we will disscuss this in tommorrow tut, there is a problem with this because use case is not suppose to know how data is stored

**Comment by Ratbuyer** [comment]
but we can merge this to master for now and change it later

**Pull request merged**
